name: Test dev env install script

on:
  pull_request:
    branches: [master]

jobs:
  test-dev-ubuntu:
    runs-on: [self-hosted, ubuntu]
    steps:
      - name: Test dev environment install on Ubuntu
        run: bash -c "$(wget --no-cache -O- https://raw.githubusercontent.com/RomainFallet/symfony-dev-ubuntu/master/ubuntu18.04_configure_dev_env.sh)"
